getgif = async () => {


    let im1 = document.getElementById("im1")
    let im2 = document.getElementById("im2")
    let im3 = document.getElementById("im3")
    let im4 = document.getElementById("im4")
    let im5 = document.getElementById("im5")
    let im6 = document.getElementById("im6")
    let im7 = document.getElementById("im7")
    let im8 = document.getElementById("im8")
    let im9 = document.getElementById("im9")
    let im10 = document.getElementById("im10")
    let im11 = document.getElementById("im11")
    let im12 = document.getElementById("im12")
    let im13 = document.getElementById("im13")
    let im14 = document.getElementById("im14")
    let im15 = document.getElementById("im15")
    let im16 = document.getElementById("im16")
    let im17 = document.getElementById("im17")
    let im18 = document.getElementById("im18")
    let im19 = document.getElementById("im19")
    let im20 = document.getElementById("im20")
    let im21 = document.getElementById("im21")
    let im22 = document.getElementById("im22")
    let im23 = document.getElementById("im23")
    let im24 = document.getElementById("im24")
    let im25 = document.getElementById("im25")
    let im26 = document.getElementById("im26")
    let im27 = document.getElementById("im27")
    let im28 = document.getElementById("im28")
    let im29 = document.getElementById("im29")
    let im30 = document.getElementById("im30")
    let im31 = document.getElementById("im31")
    let im32 = document.getElementById("im32")
    let im33 = document.getElementById("im33")
    let im34 = document.getElementById("im34")
    let im35 = document.getElementById("im35")
    let im36 = document.getElementById("im36")
    let im37 = document.getElementById("im37")
    let im38 = document.getElementById("im38")
    let im39 = document.getElementById("im39")
    let im40 = document.getElementById("im40")
    let im41 = document.getElementById("im41")
    let im42 = document.getElementById("im42")
    let im43 = document.getElementById("im43")
    let im44 = document.getElementById("im44")
    let im45 = document.getElementById("im45")
    let im46 = document.getElementById("im46")
    let im47 = document.getElementById("im47")
    let im48 = document.getElementById("im48")
    let im49 = document.getElementById("im49")
    let im50 = document.getElementById("im50")
    let image = document.getElementById("image")
    image.style.display = "flex"
    try {
        let input = document.getElementById("search")
        let search = input.value
        let api = `https://api.giphy.com/v1/gifs/search?api_key=s17aYSAC0pi9w7Six7nutWVywoGTSt3c&q=${search}&limit=50&offset=0&rating=g&lang=en`
        const response = await fetch(api)
        const jsondata = await response.json()
        const arrdata = [jsondata]
        img = arrdata[0].data[0].images.original.url
        img2 = arrdata[0].data[1].images.original.url
        img3 = arrdata[0].data[2].images.original.url
        img4 = arrdata[0].data[3].images.original.url
        img5 = arrdata[0].data[4].images.original.url
        img6 = arrdata[0].data[5].images.original.url
        img7 = arrdata[0].data[6].images.original.url
        img8 = arrdata[0].data[7].images.original.url
        img9 = arrdata[0].data[8].images.original.url
        img10 = arrdata[0].data[9].images.original.url
        img11 = arrdata[0].data[10].images.original.url
        img12 = arrdata[0].data[11].images.original.url
        img13 = arrdata[0].data[12].images.original.url
        img14 = arrdata[0].data[13].images.original.url
        img15 = arrdata[0].data[14].images.original.url
        img16 = arrdata[0].data[15].images.original.url
        img17 = arrdata[0].data[16].images.original.url
        img18 = arrdata[0].data[17].images.original.url
        img19 = arrdata[0].data[18].images.original.url
        img20 = arrdata[0].data[19].images.original.url
        img21 = arrdata[0].data[20].images.original.url
        img22 = arrdata[0].data[21].images.original.url
        img23 = arrdata[0].data[22].images.original.url
        img24 = arrdata[0].data[23].images.original.url
        img25 = arrdata[0].data[24].images.original.url
        img26 = arrdata[0].data[25].images.original.url
        img27 = arrdata[0].data[26].images.original.url
        img28 = arrdata[0].data[27].images.original.url
        img29 = arrdata[0].data[28].images.original.url
        img30 = arrdata[0].data[29].images.original.url
        img31 = arrdata[0].data[30].images.original.url
        img32 = arrdata[0].data[31].images.original.url
        img33 = arrdata[0].data[32].images.original.url
        img34 = arrdata[0].data[33].images.original.url
        img35 = arrdata[0].data[34].images.original.url
        img36 = arrdata[0].data[35].images.original.url
        img37 = arrdata[0].data[36].images.original.url
        img38 = arrdata[0].data[37].images.original.url
        img39 = arrdata[0].data[38].images.original.url
        img40 = arrdata[0].data[39].images.original.url
        img41 = arrdata[0].data[40].images.original.url
        img42 = arrdata[0].data[41].images.original.url
        img43 = arrdata[0].data[42].images.original.url
        img44 = arrdata[0].data[43].images.original.url
        img45 = arrdata[0].data[44].images.original.url
        img46 = arrdata[0].data[45].images.original.url
        img47 = arrdata[0].data[46].images.original.url
        img48 = arrdata[0].data[47].images.original.url
        img49 = arrdata[0].data[48].images.original.url
        img50 = arrdata[0].data[49].images.original.url

        console.log(img)
        im1.src = `${img}`
        im2.src = `${img2}`
        im3.src = `${img3}`
        im4.src = `${img4}`
        im5.src = `${img5}`
        im6.src = `${img6}`
        im7.src = `${img7}`
        im8.src = `${img8}`
        im9.src = `${img9}`
        im10.src = `${img10}`
        im11.src = `${img11}`
        im12.src = `${img12}`
        im13.src = `${img13}`
        im14.src = `${img14}`
        im15.src = `${img15}`
        im16.src = `${img16}`
        im17.src = `${img17}`
        im18.src = `${img18}`
        im19.src = `${img19}`
        im20.src = `${img20}`
        im21.src = `${img21}`
        im22.src = `${img22}`
        im23.src = `${img23}`
        im24.src = `${img24}`
        im25.src = `${img25}`

        im26.src = `${img26}`
        im27.src = `${img27}`
        im28.src = `${img28}`
        im29.src = `${img29}`
        im30.src = `${img30}`
        im31.src = `${img31}`
        im32.src = `${img32}`
        im33.src = `${img33}`
        im34.src = `${img34}`
        im35.src = `${img35}`
        im36.src = `${img36}`
        im37.src = `${img37}`
        im38.src = `${img38}`
        im39.src = `${img39}`
        im40.src = `${img40}`
        im41.src = `${img41}`
        im42.src = `${img42}`
        im43.src = `${img43}`
        im44.src = `${img44}`
        im45.src = `${img45}`
        im46.src = `${img46}`
        im47.src = `${img47}`
        im48.src = `${img48}`
        im49.src = `${img49}`
        im50.src = `${img50}`


    } catch (error) {

    }
}
